package com.snakelord.clickcounter;

enum CookieStates {
    STATE_FULL,
    STATE_DAMAGED_10_PERCENTS,
    STATE_DAMAGED_20_PERCENTS,
    STATE_DAMAGED_30_PERCENTS,
    STATE_DAMAGED_40_PERCENTS,
    STATE_DAMAGED_50_PERCENTS,
    STATE_DAMAGED_60_PERCENTS,
    STATE_DAMAGED_70_PERCENTS,
    STATE_DAMAGED_80_PERCENTS,
    STATE_DAMAGED_90_PERCENTS,
    STATE_DAMAGED_100_PERCENTS
}
